UPDATE RESULT_PROCESS SET `INT`='AB' WHERE `INT`=' AB';
UPDATE RESULT_PROCESS SET `EXT`='AB' WHERE `EXT`=' AB';

-- MARK RESULT ABSENT

UPDATE RESULT_PROCESS SET MARKS=`INT`+`EXT` WHERE `INT`!="AB" AND EXT!="AB";
UPDATE RESULT_PROCESS SET MARKS=EXT WHERE `INT`='AB' AND EXT!='AB';
UPDATE RESULT_PROCESS SET MARKS=`INT` WHERE `INT`!='AB' AND EXT='AB';
UPDATE RESULT_PROCESS SET MARKS=0 WHERE `EXT`='AB' AND `INT`= 'AB';

-- SET PERCENTAGE
UPDATE RESULT_PROCESS SET PERCENTAGE=(MARKS/TOTALMARKS)*100;
UPDATE RESULT_PROCESS SET PERCENTAGE=(EXT/TOTALMARKS)*100 WHERE `INT`='AB';



-- SET RESULT 
UPDATE RESULT_PROCESS SET RESULT='P' WHERE (EXT/TOTALMARKS)<=0.40 AND `INT`='AB' AND EXT!='AB';
UPDATE RESULT_PROCESS SET RESULT='P' WHERE PERCENTAGE>=40 AND `INT`='AB' AND EXT!='AB';
UPDATE RESULT_PROCESS SET RESULT='P' WHERE PERCENTAGE>=40 AND `INT`!='AB' AND EXT!='AB';
UPDATE RESULT_PROCESS SET RESULT='F' WHERE (EXT/ETOTAL)<0.40 AND `INT`='AB' AND EXT!='AB';
UPDATE RESULT_PROCESS SET RESULT='F' WHERE (EXT/TOTALMARKS)<=0.40 AND `INT`='AB' AND EXT!='AB';
UPDATE RESULT_PROCESS SET RESULT='P' WHERE PERCENTAGE>=40 AND `INT`='AB';
UPDATE RESULT_PROCESS SET RESULT='F' WHERE PERCENTAGE<=40;
UPDATE RESULT_PROCESS SET RESULT='AB' WHERE EXT='AB';
UPDATE RESULT_PROCESS SET RESULT='AB' WHERE EXT='AB' AND `INT`='AB';



-- SET GRADE
UPDATE RESULT_PROCESS SET GRADE='F' WHERE RESULT='F' OR RESULT='AB';
UPDATE RESULT_PROCESS SET GRADE='F' WHERE PERCENTAGE<=40 AND EXT!='AB';
UPDATE RESULT_PROCESS SET GRADE='E' WHERE PERCENTAGE>=40 AND PERCENTAGE<50 AND EXT!='AB';
UPDATE RESULT_PROCESS SET GRADE='D' WHERE PERCENTAGE>=50 AND PERCENTAGE<55 AND EXT!='AB';
UPDATE RESULT_PROCESS SET GRADE='C' WHERE PERCENTAGE>=55 AND PERCENTAGE<60 AND EXT!='AB';
UPDATE RESULT_PROCESS SET GRADE='B' WHERE PERCENTAGE>=60 AND PERCENTAGE<70 AND EXT!='AB';
UPDATE RESULT_PROCESS SET GRADE='A' WHERE PERCENTAGE>=70 AND PERCENTAGE<85 AND EXT!='AB';
UPDATE RESULT_PROCESS SET GRADE='O' WHERE PERCENTAGE>=85 AND PERCENTAGE<=100 AND EXT!='AB';
UPDATE RESULT_PROCESS SET GRADE='F' WHERE RESULT='F';
UPDATE RESULT_PROCESS SET GRADE='AB' WHERE RESULT='AB';

-- SET GPVV 
UPDATE RESULT_PROCESS SET GPV=PERCENTAGE/10,GPVV=PERCENTAGE/10;
UPDATE RESULT_PROCESS SET GPC=CREDITS*GPV,GPCC=CREDITS*GPVV;


-- CHECKS
SELECT * FROM `RESULT_PROCESS` WHERE PERCENTAGE<40 AND RESULT!='F' AND RESULT!='AB';
SELECT * FROM RESULT_PROCESS WHERE PERCENTAGE>40 AND (RESULT='F' OR GRADE='F');




